name: Set Environment Variables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        id: set-env
        run: |
          echo "ENV_VAR1=${{ inputs.env_var1 }}" >> $GITHUB_ENV
          echo "ENV_VAR2=${{ inputs.env_var2 }}" >> $GITHUB_ENV

      - name: Print Environment Variables
        run: |
          echo "Environment Variable 1: $ENV_VAR1"
          echo "Environment Variable 2: $ENV_VAR2"
